<a href="https://colab.research.google.com/github/abhishek-3k-ind/Tensorflow-pipeline-tf.data.Dataset/blob/main/tensorflow_pipelines_with_tf_data_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [2]:
inputs = [0,1,2,3]
outputs = [1,0,1,0]

dataset = tf.data.Dataset.from_tensor_slices((inputs, outputs))

In [3]:
for item in dataset:
  print(item)

(<tf.Tensor: shape=(), dtype=int32, numpy=0>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(), dtype=int32, numpy=2>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=3>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)


In [4]:
inputs = np.asarray([0,1,2,3])
outputs = np.asarray([1,0,1,0])

dataset = tf.data.Dataset.from_tensor_slices((inputs, outputs))

for item in dataset:
  print(item)

(<tf.Tensor: shape=(), dtype=int64, numpy=0>, <tf.Tensor: shape=(), dtype=int64, numpy=1>)
(<tf.Tensor: shape=(), dtype=int64, numpy=1>, <tf.Tensor: shape=(), dtype=int64, numpy=0>)
(<tf.Tensor: shape=(), dtype=int64, numpy=2>, <tf.Tensor: shape=(), dtype=int64, numpy=1>)
(<tf.Tensor: shape=(), dtype=int64, numpy=3>, <tf.Tensor: shape=(), dtype=int64, numpy=0>)


In [6]:
df= pd.DataFrame({
    "inputs": [0,1,2,3],
    "outputs": [1,0,1,0]
})

dataset = tf.data.Dataset.from_tensor_slices(df)

for item in dataset:
  print(item)

tf.Tensor([0 1], shape=(2,), dtype=int64)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor([2 1], shape=(2,), dtype=int64)
tf.Tensor([3 0], shape=(2,), dtype=int64)


In [ ]:
!https://github.com/abhishek-3k-ind/Tensorflow-pipeline-tf.data.Dataset.git